name: version
on:
  push:
    branches:
      - release

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.majorMinorPatch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.5.0'
      - name: Determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml

#  push-tags:
#    name: Push Tags
#    runs-on: ubuntu-latest
#    needs: tag
#    env:
#      SEMVER: ${{ needs.tag.outputs.semVer }}
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#      - name: Push tags
#        run: |
#          echo $SEMVER
#          git tag $SEMVER
#          git push origin --tags

