name: version
on:
  push:
    branches:
      - release

jobs:
  tag:
    name: Tagging
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.versioning.outputs.version_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Version
        uses: paulhatch/semantic-version@v4.0.2
        id: versioning
        with:
          tag_prefix: ""
          major_pattern: "/^(breaking|major|change): .*$/"
          minor_pattern: "/^(build|feat|enhance|fix|chore): .*$/"
          format: "${major}.${minor}.${patch}"
          short_tags: false
          bump_each_commit: false
  push_tag:
    name: Push Tag
    runs-on: ubuntu-latest
    needs: tag
    env:
      VER: ${{ needs.tag.outputs.semVer }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push Tags
        run: |
          echo $VER
          git config --global user.email "pedre@andcru.io"
          git config --global user.name "pedreviljoen"
          git tag -a $VER
          git push origin --tags