name: version
on:
  push:
    branches:
      - release

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.5.0'

  tag:
    name: Tag
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true
          configFilePath: GitVerion.yml

  push-tags:
    name: Push Tags
    runs-on: ubuntu-latest
    needs: tag
    env:
      SEMVER: ${{ needs.tag.outputs.semVer }}
    steps:
      - name: Push tags
        run: |
          echo: $SEMVER
          git push origin --tags

