name: version
on:
  push:
    branches:
      - release

jobs:
  tag:
    name: Tagging
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.majorMinorPatch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.6.5'
      - name: Determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml

  push-tags:
    name: Push Tags
    runs-on: ubuntu-latest
    needs: tag
    env:
      SEMVER: ${{ needs.tag.outputs.semVer }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push tags
        run: |
          echo $SEMVER
          git tag $SEMVER
          git push origin --tags

  release:
    name: Create release
    runs-on: ubuntu-latest
    needs:
      - tag
      - push-tags
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ needs.tag.outputs.semVer }}
          release_name: Release ${{ needs.tag.outputs.semVer }}
          body: ${{ steps.github_release.outputs.changelog }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}